### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by soorejmg** [Dwitee/mobile-cricket#4]
Hi, 
Could you help to  provide a manual on how to install and use the app. Also, details on which tool to use for development

Thanks
Soorej

**Comment by Dwitee** [comment]
Hey,
there is an apk uploaded u can install in android device.

Regards,
Dwitee

**Comment by Dwitee** [comment]
@soorejmg also you can check out project open in unity 5.x version and build to make unity or play in Unity editor.
Regards,
Dwitee

**Comment by soorejmg** [comment]
Hi Dwitee,
Thanks for this. Trying out this now. Will get more details.
Thanks
Soorej
